name: DevSecOps2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  env_var: ${{ vars.CODE_LOC }}
jobs:
  JavaCodeSecretScanning:
    runs-on: ubuntu-latest
    steps:
    - name: Env
      run: |
       echo "Var is $env_var"
