name: DevSecOps2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  CallTemplate:
    name: CallTemplate
    uses: allenjk11/ReusableTemplates/.github/workflows/SCA&SASTscan.yml@main
